name: Prepare Maven Release

on:
  push:
    branches:
      - main

jobs:
  prepare-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for tags and release plugin

      - name: Setup Git
        run: |
          git config user.name "phasetwo-bot"
          git config user.email "support@phasetwo.io"

      - name: Create release branch
        run: |
          export BRANCH_NAME=release-${{ github.run_number }}
          git checkout -b $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Run Maven release
        uses: qcastel/github-actions-maven-release@master
        with:
          release-branch-name: ${{ env.BRANCH_NAME }}
          version-patch: true

          git-release-bot-name: "phasetwo-bot"
          git-release-bot-email: "support@phasetwo.io"

          maven-args: "-B -Dmaven.test.skip=true -DskipITs -Dmaven.deploy.skip=true"

          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          gpg-enabled: true
          gpg-key-id: BC6B4EADEB514AFD
          gpg-key: ${{ secrets.GPG_KEY }}

          docker-registry-id: ossrh
          docker-registry-username: ${{ secrets.OSSRH_USERNAME }}
          docker-registry-password: ${{ secrets.OSSRH_PASSWORD }}

      - name: Push release branch
        run: git push origin ${{ env.BRANCH_NAME }}

      - name: Create Pull Request to main
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Release: ${{ env.BRANCH_NAME }}"
          branch: ${{ env.BRANCH_NAME }}
          base: main
          body: "Automated Maven release PR"
          author: phasetwo-bot <support@phasetwo.io>